name: Versioned Deployment to Lightsail

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:

  build:
    runs-on: ubuntu-latest
    outputs:
      image-version: ${{ steps.set-tag.outputs.tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Docker tag
        id: set-tag
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            TAG=${GITHUB_REF#refs/tags/}
          else
            TAG=${GITHUB_REF#refs/heads/}
          fi
          TAG=$(echo "$TAG" | tr '[:upper:]' '[:lower:]')
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-app:${{ env.TAG }}

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: dev
    steps:
      - name: Deploy to DEV via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.LIGHTSAIL_IP }}
          username: ${{ secrets.LIGHTSAIL_SSH_USER }}
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          script: |
            VERSION=${{ needs.build.outputs.image-version }}
            cd /home/ubuntu/BuyDecision/Dev
            ./start.sh $VERSION

  uat-approval:
    runs-on: ubuntu-latest
    needs: deploy-dev
    environment:
      name: uat
    steps:
      - run: echo "Waiting for UAT approval..."

  deploy-uat:
    runs-on: ubuntu-latest
    needs: uat-approval
    steps:
      - name: Deploy to UAT via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.LIGHTSAIL_IP }}
          username: ${{ secrets.LIGHTSAIL_SSH_USER }}
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          script: |
            VERSION=${{ needs.build.outputs.image-version }}
            cd /home/ubuntu/BuyDecision/UAT
            ./start.sh $VERSION

  prod-approval:
    runs-on: ubuntu-latest
    needs: deploy-uat
    environment:
      name: prod
    steps:
      - run: echo "Waiting for PROD approval..."

  deploy-prod:
    runs-on: ubuntu-latest
    needs: prod-approval
    steps:
      - name: Deploy to PROD via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.LIGHTSAIL_IP }}
          username: ${{ secrets.LIGHTSAIL_SSH_USER }}
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          script: |
            VERSION=${{ needs.build.outputs.image-version }}
            cd /home/ubuntu/BuyDecision/Prod
            ./start.sh $VERSION
